version: '2.2'

services:
  symfony_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony_app:latest
    container_name: symfony_app
    volumes:
      - ..:/var/www/html
      - /var/www/html/vendor
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      SYMFONY_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@db:3306/symfony

  db:
    image: mariadb:10.6
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
